site_name: タイムリーバドミントンクラブ

theme:
  name: material
  language: 'ja'
  logo: assets/logo.png
  feature:
    tabs: true

markdown_extensions:
  - admonition

markdown_extensions:
  - admonition
  - fontawesome_markdown
extra_css:
    - https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css"
    - "css/custom.css"

nav:
  - ホーム : index.md
  - クラブについて : about.md
  - ニュース : news.md
  - リンク: links.md
  - 練習風景: practice_image.md

google_analytics:
  - G-Q1R9PE91JZ
  - auto